spring:
  application:
    name: platform-gateway
  cloud:
    gateway:
      discovery:
        locator:
#          lower-case-service-id: true
          enabled: false
  redis:
    database: 1
    host: localhost
    port: 6379



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

server:
  port: 20004


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

