spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      server:
        git:
          force-pull: true
          uri: https://github.com/leosanqing/config-repo.git
          search-paths: '{application}'
server:
  port: 30000