server:
  #  port: 8088
  max-http-header-size: 80KB
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
  application:
    name: foodie-user-service
    ## feign 当bean名字一样时，允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    #    username: root
    #    password: root
    hikari:
      connection-timeout: 300000  # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没可用的连接则发生sql异常
      minimum-idle: 5             # 最小连接数
      maximum-pool-size: 20       # 最大连接数
      #auto-commit: true           # 自动提交
      idle-timeout: 600000        # 连接超时的最大时长(毫秒)，超过则被释放(retired)，默认::10分钟
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000       # 连接的生命时长(毫秒),默认30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
#####################
#
#   mybatis 配置
#
#####################
mybatis:
  type-aliases-package: com.leosanqing.pojo  # 所有pojo的路径
  mapper-locations: classpath:mapper/*.xml   # 所有mapper的路径

mapper:
  mappers: com.leosanqing.my.mapper.MyMapper
  not-empty: false  # 在进行数据库的操作
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

hystrix:
  command:
    # 有的属性是默认值，写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000
          # numBuckets: 10
    #        rollingPercentile:
    #          # 时间窗口统计
    #          timeInMilliseconds: 20000
    #          # numBuckets: 10
    #          bucketSize: 300
    # 照这个方法，覆盖其他的属性
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


