server:
  port: 10002
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    #    url: jdbc:mysql://10.211.55.3:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    #    password: root
    url: ${mariadb.url}
    password: ${mariadb.password}

  redis:
    database: 1
    host: localhost
    port: 6379
    # 集群
    #    cluster:
    #      nodes: 10.211.55.6:26379,10.211.55.7:26379,10.211.55.9:26379,10.211.55.10:26379,10.211.55.11:26379,10.211.55.12:26379


    # 单机单实例
    #    database: 1
    #    host: 10.211.55.12
    #    port: 6379


    # 哨兵
#    database: 0
#    sentinel:
#      master: mymaster
#      nodes: 10.211.55.12:26379,10.211.55.6:26379,10.211.55.7:26379
