spring:
  application:
    name: eureka-server

server:
  port: 30000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:30000/eureka/
  instance:
    hostname: localhost
